--- #YAML:1.0
name:                perltidy-mode
version:             0.01
abstract:            Automatically perltidies your perl source code
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_02
author:              Joshua ben Jore <jjore@cpan.org>
distribution_type:   module
requires:     
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
